export const iconList =
[
  'Accessibility', 'Activity', 'AirVent', 'Airplay', 'AlarmClockOff', 'AlarmClock', 'Album', 
  'AlignCenterHorizontal', 'AlignCenterVertical', 'AlignCenter', 'AlignEndHorizontal',  
  'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd', 'AlignHorizontalDistributeStart', 
  'AlignHorizontalJustifyCenter', 'AlignHorizontalJustifyEnd', 'AlignHorizontalJustifyStart', 
  'AlignHorizontalSpaceAround', 'AlignHorizontalSpaceBetween', 'AlignJustify', 'AlignLeft', 'AlignRight', 
  'AlignStartHorizontal', 'AlignStartVertical', 'AlignVerticalDistributeCenter', 'AlignVerticalDistributeEnd', 
  'AlignVerticalDistributeStart', 'AlignVerticalJustifyCenter', 'AlignVerticalJustifyEnd', 'AlignVerticalJustifyStart', 
  'AlignVerticalSpaceAround', 'AlignVerticalSpaceBetween', 'Ampersand', 'Ampersands', 'Anchor', 'Angry', 'Annoyed', 
  'Antenna', 'Aperture', 'AppWindow', 'Apple', 'ArchiveRestore', 'ArchiveX', 'Archive', 'AreaChart', 'Armchair', 
  'ArrowBigDownDash', 'ArrowBigDown', 'ArrowBigLeftDash', 'ArrowBigLeft', 'ArrowBigRightDash', 'ArrowBigRight', 
  'ArrowBigUpDash', 'ArrowBigUp', 'ArrowDown01', 'ArrowDown10', 'ArrowDownAZ', 'ArrowDownFromLine', 'ArrowDownLeft',
  'ArrowDownRight', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowUp01', 'ArrowUp10', 'ArrowUpAZ',
  'ArrowUpFromLine', 'ArrowUpLeft', 'ArrowUpRight', 'AttachFile', 'Attachment', 'Audio', 'Back', 'Backward',
  'Badge', 'BatteryCharging', 'BatteryFull', 'BatteryLow', 'BatteryMedium', 'Bell', 'BellOff', 'Bluetooth', 'Book', 
  'Bookmark', 'BookmarkAdd', 'BookmarkRemove', 'Briefcase', 'Brush', 'Calendar', 'Camera', 'CameraOff', 'Cancel', 
  'Car', 'Cart', 'Check', 'CheckCircle', 'CheckSquare', 'ChevronDown', 'ChevronLeft', 'ChevronRight', 'ChevronUp', 
  'Circle', 'Clipboard', 'Clock', 'Close', 'Cloud', 'CloudDownload', 'CloudUpload', 'Code', 'CodeBlock', 'Codepen', 
  'Coffee', 'Columns', 'Comment', 'Compass', 'Copy', 'CreditCard', 'Crop', 'Dashboard', 'Data', 'Delete', 'Download', 
  'DragHandle', 'Edit', 'Email', 'Expand', 'ExternalLink', 'Eye', 'EyeOff', 'Facebook', 'FastForward', 'File', 
  'FileText', 'Filter', 'Flag', 'Folder', 'FolderOpen', 'Forward', 'Gift', 'GitHub', 'Grid', 'Heart', 'HelpCircle', 
  'Home', 'Image', 'Inbox', 'Info', 'Instagram', 'Key', 'Layers', 'Link', 'LinkedIn', 'List', 'Lock', 'LogIn', 
  'LogOut', 'Mail', 'Map', 'Maximize', 'Menu', 'Message', 'Microphone', 'Minimize', 'Minus', 'MinusCircle', 
  'MinusSquare', 'Moon', 'MoreHorizontal', 'MoreVertical', 'Music', 'Navigation', 'Notification', 'Package', 'Paperclip', 
  'Pause', 'Phone', 'Play', 'Plus', 'PlusCircle', 'PlusSquare', 'Power', 'Printer', 'Radio', 'Refresh', 'Repeat', 
  'Rewind', 'Save', 'Search', 'Send', 'Settings', 'Share', 'Shield', 'ShoppingBag', 'ShoppingCart', 'Shuffle', 
  'SkipBack', 'SkipForward', 'Slack', 'Slash', 'Sliders', 'Smartphone', 'Speaker', 'Star', 'Stop', 'Sun', 'Tag', 
  'Target', 'Terminal', 'Thermometer', 'ThumbsDown', 'ThumbsUp', 'ToggleLeft', 'ToggleRight', 'Trash', 'TrendingDown', 
  'TrendingUp', 'Truck', 'Twitter', 'Unlock', 'Upload', 'User', 'UserAdd', 'UserCheck', 'UserMinus', 'UserRemove', 
  'UserX', 'Users', 'Video', 'Volume', 'Volume1', 'Volume2', 'VolumeX', 'Watch', 'Wifi', 'X', 
   'Zap', 'ZoomIn', 'ZoomOut'
];
